name: Android CI Daily Update

on:
  push:
    branches: [ "rebuild_screen" ]
  pull_request:
    branches: [ "rebuild_screen" ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        repository: cy745/lmusic
        ref: rebuild_screen
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
        submodules: true

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

